### ISSUE TITLE
Могу поделиться набросками кода boardtt

### ISSUE THREAD

**Issue by idlesign** [ru-board-games/netrunner#1]
Приветствую.

Сразу скажу, к нетраннеру никакого отношения это сообщение иметь не будет.
Этим летом сделал наброски кода, который по задумке должен был стать инструментом для локализации карт. Отлаживал на картах Star Wars.

Общая идея: 
- делаются сканы карт (карты выкладываются друг к другу на сканер);
- запускается скрипт из boardtt, натравливается на сканы;
- скрипт проходит по скану, режет его на отдельные карты;
- на карте определяет регионы с текстом, который будем локализовывать; 
- текст разбирается OCR (сейчас Tesseract);
- в директории с именем файла скана для каждой карты  создаётся json с данными карты и текстами для перевода, и оригинальное изображение карты;
- осуществляем перевод;
- запускается тот же скрипт из boardtt с теми же параметрами;
- скрипт создаёт ещё два изображения: 1. оригинал карты с локализованным текстом поверх нужных регионов (цвет подложки текста пробуем вычислить из цвета подложки оригинала); 2. оверлей, где только регионы с локализацией.

Оверлей можно отпечатать на плёнке , которую либо наклеить либо наложить на карту.
Чтобы всё это работало первым делом в терминах boardtt (классами питона) описываются регионы локализации и правила обработки карт (например, нумерация).

Сейчас код работает, однако дел ещё много:
- убрать чувствительность к смене расположения (сдвигам) карт на сканах;
- поиграться с OCR (точность на мелких текстах не очень);
- поиграться с формированием подложек;
- придумать утлицу для удобной локализации, чтобы не лезть в json;
- и пр.

Выглядит примерно так: https://yadi.sk/i/RgDeu6LpbiEuR 

В ближайшее время, вряд ли смогу уделить коду время, но если интересно, могу залить код в https://github.com/translate-board-game

**Comment by voronind** [comment]
Выглядит круто. Залить-то можно, но у меня тоже нет времени.

**Comment by idlesign** [comment]
Ладно, попозже выложу, расскажу на pythonz.net, может кого заинтересует.
Спасибо за доступ.

**Comment by idlesign** [comment]
Только там нужно ещё права выдать на возможность создания репозиториев.

**Comment by idlesign** [comment]
Закрываю, а то что-то зависелась задача %)
